version: '2'
services:
  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DEBUG=1
    networks:
      - backend
    depends_on:
      - db
  db:
    image: 'mongo'
    volumes:
      - ./mongo-volume:/data/db
    ports:
      - '27017-27019:27017-27019'
    networks:
      - backend

networks:
    backend:
